# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            'The Doc Side of the Moon'
tagline:          'Journal of a traveling Documentarian'
description:      'Journal of a traveling technical writer, Documentarian, Django Girl, FOSS advocate, geek, human.'
url:              http://docsideofthemoon.com
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Mikey Ariel'
  url:            https://twitter.com/thatdocslady

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/thatdocslady/
