# Site settings
title: 'The Doc Side of the Moon' # Your Title
tagline: 'A Traveling Documentarian blog' # A brief tagline for your site
sidebar_image: /images/sidebar.jpg
name: The Doc Side of the Moon
description: My journey as a technical writer, Red Hatter, open-source community advocate, Write the Docs documentarian, Django Girl, traveler, language nerd, geek, human.

paginate:         3
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: /strange_case # the subpath of your site, e.g. /blog/

footer-links:
  email: docs@docsideofthemoon.com
  github: thatdocslady
  twitter: ThatDocsLady
