# Setup
title:       'The Doc Side of the Moon'
tagline:     'The traveling Documentarian blog'
description: 'My journey as a technical writer, Red Hatter, open-source community advocate, Write the Docs documentarian, Django Girl, traveler, language nerd, geek, human.'
url:         http://www.docsideofthemoon.com

author:
  name:      'Mikey Ariel'
  email:     docs@docsideofthemoon.com
  github:    thatdocslady
  twitter:   ThatDocsLady

paginate:         3
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

  repo:          https://github.com/thatdocslady/thatdocslady.github.io
  permalink:     /:title/
